using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace YoutubeSharpApi.Models.Trending
{
    public class TrendingEnums
    {
        public string GetCodeOfRegion(Regions region)
        {
            string code;
            if (!_mapRegions.TryGetValue(region, out code))
            {
                throw new NullReferenceException($"Code of {nameof(region)} not found.");
            }
            return code;
        }

        public Regions GetRegionOfCode(string code)
        {
            if (_mapRegions.Any(i => i.Value == code))
            {
                return _mapRegions.First(i => i.Value == code).Key;
            }
            else
            {
                throw new NullReferenceException($"Region of {code} not found.");
            }

        }
        private static Dictionary<Regions, string> _mapRegions = new Dictionary<Regions, string>
        {
            { Regions.Algeria,"DZ"},
            { Regions.Argentina,"AR"},
            { Regions.Australia,"AU"},
            { Regions.Austria,"AT"},
            { Regions.Azerbaijan,"AZ"},
            { Regions.Bahrain,"BH"},
            { Regions.Belarus,"BY"},
            { Regions.Belgium,"BE"},
            { Regions.BosniaAndHerzegovina,"BA"},
            { Regions.Brazil,"BR"},
            { Regions.Bulgaria,"BG"},
            { Regions.Canada,"CA"},
            { Regions.Chile,"CL"},
            { Regions.Colombia,"CO"},
            { Regions.Croatia,"HR"},
            { Regions.Czechia,"CZ"},
            { Regions.Denmark,"DK"},
            { Regions.Egypt,"EG"},
            { Regions.Estonia,"EE"},
            { Regions.Finland,"FI"},
            { Regions.France,"FR"},
            { Regions.Georgia,"GE"},
            { Regions.Germany,"DE"},
            { Regions.Ghana,"GH"},
            { Regions.Greece,"GR"},
            { Regions.HongKong,"HK"},
            { Regions.Hungary,"HU"},
            { Regions.Iceland,"IS"},
            { Regions.India,"IN"},
            { Regions.Indonesia,"ID"},
            { Regions.Iraq,"IQ"},
            { Regions.Ireland,"IE"},
            { Regions.Israel,"IL"},
            { Regions.Italy,"IT"},
            { Regions.Jamaica,"JM"},
            { Regions.Japan,"JP"},
            { Regions.Jordan,"JO"},
            { Regions.Kazakhstan,"KZ"},
            { Regions.Kenya,"KE"},
            { Regions.Kuwait,"KW"},
            { Regions.Latvia,"LV"},
            { Regions.Lebanon,"LB"},
            { Regions.Libya,"LY"},
            { Regions.Lithuania,"LT"},
            { Regions.Luxembourg,"LU"},
            { Regions.Macedonia,"MK"},
            { Regions.Malaysia,"MY"},
            { Regions.Malta,"MT"},
            { Regions.Mexico,"MX"},
            { Regions.Montenegro,"ME"},
            { Regions.Morocco,"MA"},
            { Regions.Nepal,"NP"},
            { Regions.Netherlands,"NL"},
            { Regions.NewZealand,"NZ"},
            { Regions.Nigeria,"NG"},
            { Regions.Norway,"NO"},
            { Regions.Oman,"OM"},
            { Regions.Pakistan,"PK"},
            { Regions.Peru,"PE"},
            { Regions.Philippines,"PH"},
            { Regions.Poland,"PL"},
            { Regions.Portugal,"PT"},
            { Regions.PuertoRico,"PR"},
            { Regions.Qatar,"QA"},
            { Regions.Romania,"RO"},
            { Regions.Russia,"RU"},
            { Regions.SaudiArabia,"SA"},
            { Regions.Senegal,"SN"},
            { Regions.Serbia,"RS"},
            { Regions.Singapore,"SG"},
            { Regions.Slovakia,"SK"},
            { Regions.Slovenia,"SI"},
            { Regions.SouthAfrica,"ZA"},
            { Regions.SouthKorea,"KR"},
            { Regions.Spain,"ES"},
            { Regions.SriLanka,"LK"},
            { Regions.Sweden,"SE"},
            { Regions.Switzerland,"CH"},
            { Regions.Taiwan,"TW"},
            { Regions.Tanzania,"TZ"},
            { Regions.Thailand,"TH"},
            { Regions.Tunisia,"TN"},
            { Regions.Turkey,"TR"},
            { Regions.Uganda,"UG"},
            { Regions.Ukraine,"UA"},
            { Regions.UnitedArabEmirates,"AE"},
            { Regions.UnitedKingdom,"GB"},
            { Regions.UnitedStates,"US"},
            { Regions.Vietnam,"VN"},
            { Regions.Yemen,"YE"},
            { Regions.Zimbabwe,"ZW"},
        };
        public enum Regions
        {
            Algeria,
            Argentina,
            Australia,
            Austria,
            Azerbaijan,
            Bahrain,
            Belarus,
            Belgium,
            BosniaAndHerzegovina,
            Brazil,
            Bulgaria,
            Canada,
            Chile,
            Colombia,
            Croatia,
            Czechia,
            Denmark,
            Egypt,
            Estonia,
            Finland,
            France,
            Georgia,
            Germany,
            Ghana,
            Greece,
            HongKong,
            Hungary,
            Iceland,
            India,
            Indonesia,
            Iraq,
            Ireland,
            Israel,
            Italy,
            Jamaica,
            Japan,
            Jordan,
            Kazakhstan,
            Kenya,
            Kuwait,
            Latvia,
            Lebanon,
            Libya,
            Lithuania,
            Luxembourg,
            Macedonia,
            Malaysia,
            Malta,
            Mexico,
            Montenegro,
            Morocco,
            Nepal,
            Netherlands,
            NewZealand,
            Nigeria,
            Norway,
            Oman,
            Pakistan,
            Peru,
            Philippines,
            Poland,
            Portugal,
            PuertoRico,
            Qatar,
            Romania,
            Russia,
            SaudiArabia,
            Senegal,
            Serbia,
            Singapore,
            Slovakia,
            Slovenia,
            SouthAfrica,
            SouthKorea,
            Spain,
            SriLanka,
            Sweden,
            Switzerland,
            Taiwan,
            Tanzania,
            Thailand,
            Tunisia,
            Turkey,
            Uganda,
            Ukraine,
            UnitedArabEmirates,
            UnitedKingdom,
            UnitedStates,
            Vietnam,
            Yemen,
            Zimbabwe,

        }
        public enum Categories
        {
            FilmAnimation = 1,
            AutosVehicles = 2,
            Music = 10,
            PetsAnimals = 15,
            Sports = 17,
            ShortMovies = 18,
            TravelEvents = 19,
            Gaming = 20,
            Videoblogging = 21,
            PeopleBlogs = 22,
            Comedy_23 = 23,
            Entertainment = 24,
            NewsPolitics = 25,
            HowtoStyle = 26,
            Education = 27,
            ScienceTechnology = 28,
            NonprofitsActivism = 29,
            Movies = 30,
            AnimeAnimation = 31,
            ActionAdventure = 32,
            Classics = 33,
            Comedy_34 = 34,
            Documentary = 35,
            Drama = 36,
            Family = 37,
            Foreign = 38,
            Horror = 39,
            SciFiFantasy = 40,
            Thriller = 41,
            Shorts = 42,
            Shows = 43,
            Trailers = 44,



        }
    }
}
